name: CI/CD Laravel

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      APP_ENV: testing
      APP_DEBUG: "false"
      APP_URL: http://localhost
      APP_LOCALE: en
      APP_FALLBACK_LOCALE: en
      APP_FAKER_LOCALE: en_US
      BCRYPT_ROUNDS: "4"
      LOG_CHANNEL: stack
      LOG_LEVEL: debug

      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"

      SESSION_DRIVER: array
      SESSION_LIFETIME: "120"
      SESSION_ENCRYPT: "false"

      BROADCAST_CONNECTION: log
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync

      CACHE_STORE: array
      CACHE_DRIVER: array

      MAIL_MAILER: array

      PULSE_ENABLED: "false"
      TELESCOPE_ENABLED: "false"

      STRIPE_CURRENCY: pln
    services:
      sqlite:
        image: nouchka/sqlite3:latest
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_sqlite, bcmath, gd, xml
          coverage: none

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Clean npm artifacts
        run: |
          rm -rf node_modules package-lock.json || true
          npm cache clean --force || true

      - name: Install NPM dependencies (include optional native binaries)
        run: |
          npm install

      - name: PHP Lint (Pint)
        run: ./vendor/bin/pint --test

      - name: JS Lint (ESLint)
        run: |
          if [ -f node_modules/.bin/eslint ]; then
            npx eslint resources/js || exit 1
          else
            echo "No ESLint found, skipping JS lint."
          fi

      - name: Build assets
        run: npm run build

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Generate Laravel key
        run: php artisan key:generate

      - name: Generate APP_KEY for tests and write .env.testing
        run: |
          # Generate a valid APP_KEY and write it to GITHUB_ENV for later steps
          APP_KEY_VALUE=$(php artisan key:generate --show)
          echo "APP_KEY=${APP_KEY_VALUE}" >> $GITHUB_ENV

          # Write a minimal .env.testing file directly using the generated key so
          # Laravel picks up a valid APP_KEY and test-friendly settings regardless
          # of dotenv loading order on the runner.
          cat > .env.testing <<EOF
          APP_NAME=FoodOrder
          APP_ENV=testing
          APP_KEY=${APP_KEY_VALUE}
          APP_DEBUG=false
          APP_URL=http://localhost

          DB_CONNECTION=sqlite
          DB_DATABASE=:memory:

          SESSION_DRIVER=array
          CACHE_DRIVER=array
          QUEUE_CONNECTION=sync

          MAIL_MAILER=array
          EOF

          # Also ensure the primary .env has the same APP_KEY so any processes
          # that read .env (instead of .env.testing) still see a valid key.
          if [ -f .env ]; then
            # Remove any existing APP_KEY lines and append the new one
            sed -i "/^APP_KEY=/d" .env || true
          else
            cp .env.example .env || true
          fi
          echo "APP_KEY=${APP_KEY_VALUE}" >> .env
          # Remove any leading indentation that may have been introduced by YAML
          # so that dotenv parsing sees keys starting at column 1.
          sed -i 's/^[[:space:]]*//' .env.testing || true
          sed -i 's/^[[:space:]]*//' .env || true

      - name: Clear config/cache so APP_KEY is loaded
        run: |
          php artisan config:clear || true
          php artisan cache:clear || true

      - name: Run migrations
        run: php artisan migrate --env=testing

      - name: Run tests
        run: php artisan test --env=testing

  docker-push:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/food-ordering-platform:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/food-ordering-platform:latest
